



from django.urls import path
from rest_framework.routers import DefaultRouter

from quiz_app.api.views import QuizViewSet


router = DefaultRouter()
# Register the QuizViewSet and automatically generate REST routes
router.register(r'quizzes', QuizViewSet, basename="quiz")


# URL patterns generated by the router (CRUD endpoints for quizzes)
urlpatterns = router.urls